var partitura = [
  {
    name:   "Redonda",
    image:  "./img/redonda.png",
    sonido: "undefine" },
  { name:   "Blanca",
    image:  "./img/blanca.svg" ,
    sonido: "undefine"  },
  //{ name:   "Negra",
  //  image:  "undefine",
  //  sonido: "undefine" },
  //{ name:   "Doble Corchea",
  //  image:  "undefine",
  //  sonido: "undefine" },
  //{ name:   "Cuaterna SemiCorchea",
  //  image:  "undefine",
  //  sonido: "undefine" },
  //{ name:   "SemiCorchea",
  //  image:  "undefine",
  //  sonido: "undefine" },
  //{ name:   "Corchea",
  //  image:  "undefine",
  //  sonido: "undefine" },
  //{ name:   "Silencio",
  //  image:  "undefine",
  //  sonido: "undefine" },
]