var partitura = [
  {
    name:   "Redonda",
    image:  "./img/symbols/redonda.png",
    sonido: "undefine" },
  { name:   "Blanca",
    image:  "./img/symbols/blanca.png" ,
    sonido: "undefine"  },
  { name:   "Negra",
    image:  "./img/symbols/negra.png",
    sonido: "undefine" },
  //{ name:   "Doble Corchea",
  //  image:  "./img/symbols/blanca.svg",
  //  sonido: "undefine" },
  //{ name:   "Cuaterna SemiCorchea",
  //  image:  "./img/symbols/blanca.svg",
  //  sonido: "undefine" },
  //{ name:   "SemiCorchea",
  //  image:  "./img/symbols/blanca.svg",
  //  sonido: "undefine" },
  //{ name:   "Corchea",
  //  image:  "./img/symbols/blanca.svg",
  //  sonido: "undefine" },
  //{ name:   "Silencio de Blanca",
  //  image:  "./img/symbols/silencioBlanca.png",
  //  sonido: "undefine" },
  { name:   "Silencio de Redonda",
    image:  "./img/symbols/silencioRedonda.png",
    sonido: "undefine" },

]